Major updates:
1. Migrated most functions to internal-functions directory  
2. Introduced new env var ICA_ICA_LAZY_HOME,  which should be set to ~/.ica-ica-lazy  
3. Use gwc over wc for macs.  
4. Use gbase64 over base64 for macs

diff --git a/scripts/gds-blame b/scripts/gds-blame
--- a/scripts/gds-blame
+++ b/scripts/gds-blame
@@ -8,10 +8,7 @@ If thats not possible, just return the user that created directory, and when the
 # Set to fail
 set -euo pipefail
 
-# Globals
-MAX_PAGE_SIZE=200
-SECONDS_PER_WEEK="604800"
-
+# Functions
 # Help function
 print_help(){
   echo "
@@ -31,11 +28,6 @@ print_help(){
         "
 }
 
-## Internal functions
-echo_stderr(){
-  echo "$@" 1>&2
-}
-
 binaries_check(){
   : '
   Check each of the required binaries are available
@@ -43,271 +35,6 @@ binaries_check(){
   if ! (type jq python3 curl 1>/dev/null); then
     return 1
   fi
-}
-
-get_sed_command(){
-  if [[ "${OSTYPE}" == "darwin"* ]]; then
-    echo "gsed"
-  else
-    echo "sed"
-  fi
-}
-
-get_epoch_expiry(){
-  : '
-  Get the epoch value of the expiry date of the tokens
-  '
-  local access_token="$1"
-  echo "${access_token}" | \
-    "$(get_sed_command)" -r 's/^(\S+)\.(\S+)\.(\S+)$/\2/' | \
-    ( base64 -d 2>/dev/null || true ) | \
-    jq -r '.exp'
-}
-
-get_seconds_to_expiry(){
-  : '
-  Get seconds to expiry based on epoch time
-  '
-  local expiry_epoch="$1"
-  bc <<< "${expiry_epoch} - $(date +%s)"
-}
-
-warn_time_to_expiry(){
-  : '
-  Convert the epoch time to expiry to a readable date format
-  '
-  local expiry_in_seconds="$1"
-
-  python3 -c "from datetime import timedelta; from sys import stderr; \
-              time_to_expiry=timedelta(seconds=${expiry_in_seconds}); \
-              d = {'days': time_to_expiry.days}; \
-              d['hours'], rem = divmod(time_to_expiry.seconds, 3600); \
-              d['minutes'], d['seconds'] = divmod(rem, 60); \
-              print('Expired') if ${expiry_in_seconds} < 0 \
-              else print(f\"Warning: Your ica access token will end in {d['days']} days, {d['hours']} hours, {d['minutes']} minutes, {d['seconds']} seconds\", file=stderr)"
-}
-
-get_parent_path(){
-  : '
-  Take the path input as a python lib and then return the parent (with a trailing slash)
-  '
-
-  local gds_path_attr="$1"
-
-  python3 -c "from pathlib import Path; print(str(Path(\"${gds_path_attr}\").parent).rstrip(\"/\") + \"/\")"
-}
-
-check_volume(){
-  : '
-  Confirm the volume exists
-  '
-  local volume_name="$1"
-
-  if ! curl \
-         --silent \
-         --location \
-         --fail \
-         --request GET \
-         --header 'Accept: application/json' \
-         --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-         --url "${ICA_BASE_URL}/v1/volumes/${volume_name}" \
-         --get >/dev/null 2>&1; then
-    return 1
-  else
-    return 0
-  fi
-}
-
-check_token_expiry(){
-  : '
-  Return the expiry in printable format
-  '
-  # Inputs
-  local access_token="$1"
-
-  # local vars
-  local epoch_expiry
-  local seconds_to_expiry
-
-  # Get the JWT token expiry time
-  epoch_expiry="$(get_epoch_expiry "${access_token}")"
-
-  # Compare expiry to current time
-  seconds_to_expiry="$(get_seconds_to_expiry "${epoch_expiry}")"
-
-  # Check token expiry
-  if [[ "${seconds_to_expiry}" -le 0 ]]; then
-    # Token has expired
-    echo_stderr "Error - Your access token has expired! Please refresh with 'ica-add-access-token'"
-    exit 1
-  elif [[ "${seconds_to_expiry}" -le "${SECONDS_PER_WEEK}" ]]; then
-    # Warn user token expires in less than a week
-    echo_stderr "$(warn_time_to_expiry "${seconds_to_expiry}")"
-  fi
-}
-
-# Get volume from gds path
-get_volume_from_gds_path() {
-  : '
-  Assumes urllib is available on python3
-  '
-  local gds_path="$1"
-
-  # Returns the netloc attribute of the gds_path
-  python3 -c "from urllib.parse import urlparse; print(urlparse(\"${gds_path}\").netloc)"
-}
-
-# Get folder path
-get_folder_path_from_gds_path() {
-  : '
-  Assumes urllib is available on python3
-  '
-  local gds_path="$1"
-
-  # Returns the path attribute of gds_path input
-  python3 -c "from urllib.parse import urlparse; from pathlib import Path; print(str(Path(urlparse(\"${gds_path}\").path)).rstrip(\"/\") + \"/\")"
-}
-
-get_workflow_run_ids(){
-  : '
-  Get the list of workflow run ids
-  '
-  local response
-  local next_page_token
-  local url
-
-  # Initalise next_page_token
-  next_page_token="null"
-
-  while :; do
-    url="${ICA_BASE_URL}/v1/workflows/runs?status=succeeded&pageSize=${MAX_PAGE_SIZE}"
-    if [[ ! "${next_page_token}" == "null" ]]; then
-      url="${url}&pageToken=${next_page_token}"
-    fi
-    response="$(curl \
-      --silent \
-      --fail \
-      --location \
-      --request GET \
-      --header "Accept: application/json" \
-      --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-      --url "${url}")"
-
-    # Print existing items
-    jq --raw-output --compact-output '.items[] | .id' <<< "${response}"
-
-    # Assign token
-    next_page_token="$(jq -r '.nextPageToken' <<< "${response}")"
-
-    # Break if no more items
-    if [[ "${next_page_token}" == "null" ]]; then
-      break
-    fi
-  done
-}
-
-get_engine_parameters(){
-  : '
-  Use engine parameters to pull down the workflow
-  '
-  local ica_workflow_run_id="$1"
-  curl \
-    --silent \
-    --fail \
-    --location \
-    --request GET \
-    --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-    "${ICA_BASE_URL}/v1/workflows/runs/${ica_workflow_run_id}/?include=engineParameters" | \
-  jq \
-    --raw-output \
-    '.engineParameters | fromjson'
-}
-
-get_folder_id(){
-  : '
-  Check if the current path is a folder by first listing the folders in the parent path
-  and searching for this folder
-  '
-
-  local volume_name="$1"
-  local gds_path_attr="$2"
-  local data_params=( "--data" "volume.name=${volume_name}"
-                      "--data" "recursive=false"
-                      "--data" "pageSize=${MAX_PAGE_SIZE}" )
-
-  if [[ -z "${gds_path_attr}" || "${gds_path_attr}" == "/" ]]; then
-    # Check volume exists
-    if ! check_volume "${volume_name}"; then
-      return 1
-    else
-      return 0
-    fi
-  fi
-
-
-  if [[ -n "${gds_path_attr}" && "${gds_path_attr}" != "/" ]]; then
-    data_params+=( "--data" "path=$(get_parent_path "${gds_path_attr}")*" )
-  fi
-
-  if ! folders_obj="$(curl \
-                        --silent \
-                        --location \
-                        --fail \
-                        --request GET \
-                        --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-                        --url "${ICA_BASE_URL}/v1/folders" \
-                        --get \
-                        "${data_params[@]}" 2>/dev/null)"; then
-    return 1
-  fi
-
-  if [[ "$(jq \
-            --raw-output \
-            --arg "gds_path_attr" "${gds_path_attr}" \
-            '.items[] | select ( .path == $gds_path_attr ) | .path' <<< "${folders_obj}")" != "${gds_path_attr}" ]]; then
-      return 1
-  fi
-
-  jq \
-    --raw-output \
-    --arg "gds_path_attr" "${gds_path_attr}" \
-    '.items[] | select ( .path == $gds_path_attr ) | .id' <<< "${folders_obj}"
-}
-
-get_folder_creator_username(){
-  : '
-  Given the id of a folder, return the user name of the creator of that folder.
-  This is achieved by running a get on the folder path, followed by
-  a get on the createdBy id on the accounts api
-  '
-
-  local folder_id="$1"
-  local creator_account_id
-
-  creator_account_id="$(curl \
-                         --silent \
-                         --location \
-                         --fail \
-                         --request GET \
-                         --header "Accept: application/json" \
-                         --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-                         --url "${ICA_BASE_URL}/v1/folders/${folder_id}" | \
-                       jq \
-                         --raw-output \
-                         '.createdBy')"
-
-  # Use accounts endpoint with creator account id
-  curl \
-    --silent \
-    --location \
-    --fail \
-    --request GET \
-    --header "Accept: application/json" \
-    --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-    --url "${ICA_BASE_URL}/v1/accounts/${creator_account_id}" | \
-  jq \
-    --raw-output \
-    '.name'
 }
 
 create_workflow_run_summary_header(){
@@ -339,6 +66,23 @@ while [ $# -gt 0 ]; do
   shift 1
 done
 
+###########ICA-ICA-LAZY SETUP ########################################
+
+if [[ -z "${ICA_ICA_LAZY_HOME-}" ]]; then
+  echo "Error - please ensure env var 'ICA_ICA_LAZY_HOME' is set" 1>&2
+  exit 1
+fi
+
+if [[ -d "${ICA_ICA_LAZY_HOME}/internal-functions" ]]; then
+  for f in "${ICA_ICA_LAZY_HOME}/internal-functions/"*".sh"; do
+      # shellcheck source=../internal-functions/*.sh
+      source "$f"
+  done
+fi
+
+##########END ICA-ICA-LAZY SETUP ####################################
+
+
 # Ensure gds_path param is set
 if [[ -z "${gds_path}" ]]; then
   echo_stderr "Please make sure --gds-path parameter is set"
@@ -365,18 +109,18 @@ check_token_expiry "${ICA_ACCESS_TOKEN}"
 volume_name="$(get_volume_from_gds_path "${gds_path}")"
 folder_path="$(get_folder_path_from_gds_path "${gds_path}")"
 gds_path="gds://${volume_name}${folder_path}"  # Comes with trailing slash
-if ! folder_id="$(get_folder_id "${volume_name}" "${folder_path}")"; then
+if ! folder_id="$(get_folder_id "${volume_name}" "${folder_path}" "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}")"; then
   echo_stderr "Error: Directory '${gds_path}' does not exist."
   exit 1
 fi
 # Show creator
-creator_username="$(get_folder_creator_username "${folder_id}")"
+creator_username="$(get_folder_creator_username "${folder_id}" "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}")"
 
 echo "The directory '${gds_path}' was created by user '${creator_username}'"
 echo "Now checking if this directory was created by a workflow run."
 
 # Read the array of workflow ids
-readarray -t workflow_run_id_array < <(get_workflow_run_ids)
+readarray -t workflow_run_id_array < <(get_workflow_run_ids "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}")
 
 # We only print the header of 'this directory was created by the following workflow run ids if one present'
 has_match=0
@@ -392,7 +136,7 @@ for workflow_run_id in "${workflow_run_id_array[@]}"; do
   fi
   workflow_run_counter="$((workflow_run_counter + 1))"
   # Get engine parameters
-  engine_parameters="$(get_engine_parameters "${workflow_run_id}")"
+  engine_parameters="$(get_engine_parameters_from_workflow_id "${workflow_run_id}" "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}")"
 
   # Get directories
   output_directory="$(jq --raw-output '.outputDirectory' <<< "${engine_parameters}")/"
@@ -426,7 +170,6 @@ for workflow_run_id in "${workflow_run_id_array[@]}"; do
     has_match=1
     echo "Input argument '${gds_path}' is a parent of '${working_directory}' which is the output directory for run '${workflow_run_id}'"
   fi
-
 done
 
 if [[ "${has_match}" == "0" ]]; then
diff --git a/scripts/gds-find b/scripts/gds-find
--- a/scripts/gds-find
+++ b/scripts/gds-find
@@ -7,9 +7,7 @@ Credit where credit is due:
 * https://til.hashrocket.com/posts/uv0bjiokwk-use-jq-to-filter-objects-list-with-regex
 '
 
-# Globals
-MAX_PAGE_SIZE=1000
-SECONDS_PER_WEEK="604800"
+set -euo pipefail
 
 # Help function
 print_help(){
@@ -37,11 +35,6 @@ print_help(){
         "
 }
 
-## Internal functions
-echo_stderr(){
-  echo "$@" 1>&2
-}
-
 binaries_check(){
   : '
   Check each of the required binaries are available
@@ -49,286 +42,6 @@ binaries_check(){
   if ! (type jq python3 curl 1>/dev/null); then
     return 1
   fi
-}
-
-get_sed_command(){
-  if [[ "${OSTYPE}" == "darwin"* ]]; then
-    echo "gsed"
-  else
-    echo "sed"
-  fi
-}
-
-get_epoch_expiry(){
-  : '
-  Get the epoch value of the expiry date of the tokens
-  '
-  local access_token="$1"
-  echo "${access_token}" | \
-    "$(get_sed_command)" -r 's/^(\S+)\.(\S+)\.(\S+)$/\2/' | \
-    ( base64 -d 2>/dev/null || true ) | \
-    jq -r '.exp'
-}
-
-get_seconds_to_expiry(){
-  : '
-  Get seconds to expiry based on epoch time
-  '
-  local expiry_epoch="$1"
-  bc <<< "${expiry_epoch} - $(date +%s)"
-}
-
-warn_time_to_expiry(){
-  : '
-  Convert the epoch time to expiry to a readable date format
-  '
-  local expiry_in_seconds="$1"
-
-  python3 -c "from datetime import timedelta; from sys import stderr; \
-              time_to_expiry=timedelta(seconds=${expiry_in_seconds}); \
-              d = {'days': time_to_expiry.days}; \
-              d['hours'], rem = divmod(time_to_expiry.seconds, 3600); \
-              d['minutes'], d['seconds'] = divmod(rem, 60); \
-              print('Expired') if ${expiry_in_seconds} < 0 \
-              else print(f\"Warning: Your ica access token will end in {d['days']} days, {d['hours']} hours, {d['minutes']} minutes, {d['seconds']} seconds\", file=stderr)"
-}
-
-check_token_expiry(){
-  : '
-  Return the expiry in printable format
-  '
-  # Inputs
-  local access_token="$1"
-
-  # local vars
-  local epoch_expiry
-  local seconds_to_expiry
-
-  # Get the JWT token expiry time
-  epoch_expiry="$(get_epoch_expiry "${access_token}")"
-
-  # Compare expiry to current time
-  seconds_to_expiry="$(get_seconds_to_expiry "${epoch_expiry}")"
-
-  # Check token expiry
-  if [[ "${seconds_to_expiry}" -le 0 ]]; then
-    # Token has expired
-    echo_stderr "Error - Your access token has expired! Please refresh with 'ica-add-access-token'"
-    exit 1
-  elif [[ "${seconds_to_expiry}" -le "${SECONDS_PER_WEEK}" ]]; then
-    # Warn user token expires in less than a week
-    echo_stderr "$(warn_time_to_expiry "${seconds_to_expiry}")"
-  fi
-}
-
-# Get volume from gds path
-get_volume_from_gds_path() {
-  : '
-  Assumes urllib is available on python3
-  '
-  local gds_path="$1"
-
-  # Returns the netloc attribute of the gds_path
-  python3 -c "from urllib.parse import urlparse; print(urlparse(\"${gds_path}\").netloc)"
-}
-
-# Get folder path
-get_folder_path_from_gds_path() {
-  : '
-  Assumes urllib is available on python3
-  '
-  local gds_path="$1"
-
-  # Returns the path attribute of gds_path input
-  python3 -c "from urllib.parse import urlparse; from pathlib import Path; print(str(Path(urlparse(\"${gds_path}\").path)).rstrip(\"/\") + \"/\")"
-}
-
-# Get the parent path
-get_parent_path(){
-  : '
-  Take the path input as a python lib and then return the parent (with a trailing slash)
-  '
-
-  local gds_path_attr="$1"
-
-  python3 -c "from pathlib import Path; print(str(Path(\"${gds_path_attr}\").parent).rstrip(\"/\") + \"/\")"
-}
-
-check_volume(){
-  : '
-  Confirm the volume exists
-  '
-  local volume_name="$1"
-
-  if ! curl \
-         --silent \
-         --location \
-         --fail \
-         --request GET \
-         --header 'Accept: application/json' \
-         --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-         --url "${ICA_BASE_URL}/v1/volumes/${volume_name}" \
-         --get >/dev/null 2>&1; then
-    return 1
-  else
-    return 0
-  fi
-}
-
-check_path_is_folder(){
-  : '
-  Check if the current path is a folder by first listing the folders in the parent path
-  and searching for this folder
-  '
-
-  local volume_name="$1"
-  local gds_path_attr="$2"
-  local data_params=( "--data" "volume.name=${volume_name}"
-                      "--data" "recursive=false"
-                      "--data" "pageSize=${MAX_PAGE_SIZE}" )
-
-  if [[ -z "${gds_path_attr}" || "${gds_path_attr}" == "/" ]]; then
-    # Check volume exists
-    if ! check_volume "${volume_name}"; then
-      return 1
-    else
-      return 0
-    fi
-  fi
-
-
-  if [[ -n "${gds_path_attr}" && "${gds_path_attr}" != "/" ]]; then
-    data_params+=( "--data" "path=$(get_parent_path "${gds_path_attr}")*" )
-  fi
-
-  if ! folders_obj="$(curl \
-                        --silent \
-                        --location \
-                        --fail \
-                        --request GET \
-                        --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-                        --url "${ICA_BASE_URL}/v1/folders" \
-                        --get \
-                        "${data_params[@]}" 2>/dev/null)"; then
-    return 1
-  fi
-
-  if [[ "$(jq \
-            --raw-output \
-            --arg "gds_path_attr" "${gds_path_attr}" \
-            '.items[] | select ( .path == $gds_path_attr ) | .path' <<< "${folders_obj}")" != "${gds_path_attr}" ]]; then
-      return 1
-  fi
-}
-
-get_file_names(){
-  : '
-  list the files and the subfolders of the path that match
-  '
-  local volume_name="$1"
-  local gds_path_attr="$2"
-  local name="$3"
-  local files_obj
-  local files
-
-  files_obj="$(curl \
-                 --silent \
-                 --location \
-                 --fail \
-                 --request GET \
-                 --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-                 --url "${ICA_BASE_URL}/v1/files" \
-                 --get \
-                 --data "volume.name=${volume_name}" \
-                 --data "recursive=false" \
-                 --data "pageSize=${MAX_PAGE_SIZE}" \
-                 --data "path=${gds_path_attr}*" 2>/dev/null)"
-
-  files="$(jq --raw-output \
-             --arg "volume_name" "${volume_name}" \
-             --arg "name" "${name}" \
-             '.items[] | select(.name | test($name)) | "gds://\($volume_name)\(.path)"' <<< "${files_obj}")"
-
-  printf "%s" "${files}" | sort -f
-}
-
-get_subfolder_names(){
-  : '
-  list the files and the subfolders of the path that match
-  '
-  local volume_name="$1"
-  local gds_path_attr="$2"
-  local name="$3"
-  local folders_obj
-  local folders
-
-  # Get folders and files
-  folders_obj="$(curl \
-                   --silent \
-                   --location \
-                   --fail \
-                   --request GET \
-                   --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-                   --url "${ICA_BASE_URL}/v1/folders" \
-                   --get \
-                   --data "volume.name=${volume_name}" \
-                   --data "recursive=false" \
-                   --data "pageSize=${MAX_PAGE_SIZE}" \
-                   --data "path=${gds_path_attr}*" 2>/dev/null)"
-
-  if [[ -z "${name}" ]]; then
-    # We're returning the path
-    jq --compact-output --raw-output \
-      '.items[] | .path' <<< "${folders_obj}"
-  else
-    # We're printing the outputs with the volume name included
-    folders="$(jq --raw-output \
-                 --arg "volume_name" "${volume_name}" \
-                 --arg "name" "${name}" \
-                 '.items[] | select(.name|test($name)) | "gds://\($volume_name)\(.path)"' <<< "${folders_obj}")"
-    printf "%s" "${folders}" | sort -f
-  fi
-}
-
-gds_search(){
-  : '
-  Recursively list and print all files / directories with the existing dirs
-  '
-  local volume_name="$1"
-  local folder_path="$2"
-  local depth="$3"
-  local mindepth="$4"
-  local maxdepth="$5"
-  local type="$6"
-  local name="$7"
-  local subfolder_paths_array=()
-
-  # Check we haven't depthed too far
-  if [[ "${maxdepth}" != "-1" && "${maxdepth}" -le "${depth}" ]]; then
-    # We've gone too far
-    return 0
-  fi
-
-  # If we're within 'range' of printing files / dirs, then do so
-  if [[ ( "${mindepth}" == "-1" || "${mindepth}" -le "${depth}" ) && ( "${maxdepth}" == "-1" || "${depth}" -le "${maxdepth}" ) ]]; then
-    if [[ "${type}" == "directory" ]]; then
-      get_subfolder_names "${volume_name}" "${folder_path}" "${name}"
-    else
-      get_file_names "${volume_name}" "${folder_path}" "${name}"
-    fi
-  fi
-
-  # We're still not beyond the maximum depth
-  depth="$(expr "${depth}" + 1)"
-
-  # Recollect the array of subfolders
-  readarray -t subfolder_paths_array < <(get_subfolder_names "${volume_name}" "${folder_path}")
-
-  # Iterate through array
-  for subfolder_path in "${subfolder_paths_array[@]}"; do
-    # echo_stderr "Checking folder gds://${volume_name}/${subfolder_path}"  # FIXME - add in as a debug parameter
-    gds_search "${volume_name}" "${subfolder_path}" "${depth}" "${mindepth}" "${maxdepth}" "${type}" "${name}"
-  done
 }
 
 # Get args
@@ -368,6 +81,22 @@ while [ $# -gt 0 ]; do
   esac
   shift 1
 done
+
+###########ICA-ICA-LAZY SETUP ########################################
+
+if [[ -z "${ICA_ICA_LAZY_HOME-}" ]]; then
+  echo "Error - please ensure env var 'ICA_ICA_LAZY_HOME' is set" 1>&2
+  exit 1
+fi
+
+if [[ -d "${ICA_ICA_LAZY_HOME}/internal-functions" ]]; then
+  for f in "${ICA_ICA_LAZY_HOME}/internal-functions/"*".sh"; do
+      # shellcheck source=../internal-functions/*.sh
+      source "$f"
+  done
+fi
+
+##########END ICA-ICA-LAZY SETUP ####################################
 
 # Check and set args
 if [[ -z "${type}" ]]; then
@@ -438,9 +167,9 @@ name="${name//\./\\.}"
 # Place literal '^' at start and '$' at end of name
 name="^${name}\$"
 
-if ! check_path_is_folder "${volume_name}" "${folder_path}"; then
+if ! check_path_is_folder "${volume_name}" "${folder_path}" "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"; then
   echo_stderr "Could not find directory '${gds_path}'"
   exit 1
 fi
 
-gds_search "${volume_name}" "${folder_path}" "0" "${mindepth}" "${maxdepth}" "${type}" "${name}"
+gds_search "${volume_name}" "${folder_path}" "0" "${mindepth}" "${maxdepth}" "${type}" "${name}" "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"
diff --git a/scripts/gds-ls b/scripts/gds-ls
--- a/scripts/gds-ls
+++ b/scripts/gds-ls
@@ -10,128 +10,11 @@ This script does the following
 
 set -euo pipefail
 
-#########
-# GLOBALS
-#########
-
-MAX_PAGE_SIZE=1000
-SECONDS_PER_WEEK="604800"
-
 ###########
 # FUNCTIONS
 ###########
 
 ## Getters
-echo_stderr(){
-  echo "$@" 1>&2
-}
-
-get_volume_name(){
-  : '
-  Get the volume name from the gds path
-  '
-
-  # Function outputs
-  python3 -c "from urllib.parse import urlparse; print(urlparse(\"${gds_path}\").netloc)"
-}
-
-get_path(){
-  : '
-  Get the path attribute from the gds path
-  '
-
-  # Function outputs
-  python3 -c "from urllib.parse import urlparse; from pathlib import Path; print(str(Path(urlparse(\"${gds_path}\").path)).rstrip(\"/\") + \"/\")"
-
-}
-
-get_parent_path(){
-  : '
-  Take the path input as a python lib and then return the parent (with a trailing slash)
-  '
-
-  local gds_path_attr="$1"
-
-  python3 -c "from pathlib import Path; print(str(Path(\"${gds_path_attr}\").parent).rstrip(\"/\") + \"/\")"
-}
-
-get_sed_command(){
-  if [[ "${OSTYPE}" == "darwin"* ]]; then
-    echo "gsed"
-  else
-    echo "sed"
-  fi
-}
-
-get_epoch_expiry(){
-  : '
-  Get the epoch value of the expiry date of the tokens
-  '
-  local access_token="$1"
-  local epoch_expiry
-  epoch_expiry="$(echo "${access_token}" | \
-                  "$(get_sed_command)" -r 's/^(\S+)\.(\S+)\.(\S+)$/\2/' | \
-                  ( base64 -d 2>/dev/null || true ) | \
-                  jq -r '.exp' 2>/dev/null)"
-
-  if [[ "${epoch_expiry}" -le "0" ]]; then
-    echo_stderr "Token has expired!"
-  fi
-
-  echo "${epoch_expiry}"
-}
-
-get_seconds_to_expiry(){
-  : '
-  Get seconds to expiry based on epoch time
-  '
-  local expiry_epoch="$1"
-  bc <<< "${expiry_epoch} - $(date +%s)"
-}
-
-warn_time_to_expiry(){
-  : '
-  Convert the epoch time to expiry to a readable date format
-  '
-  local expiry_in_seconds="$1"
-
-  python3 -c "from datetime import timedelta; from sys import stderr; \
-              time_to_expiry=timedelta(seconds=${expiry_in_seconds}); \
-              d = {'days': time_to_expiry.days}; \
-              d['hours'], rem = divmod(time_to_expiry.seconds, 3600); \
-              d['minutes'], d['seconds'] = divmod(rem, 60); \
-              print('Expired') if ${expiry_in_seconds} < 0 \
-              else print(f\"Warning: Your ica access token will end in {d['days']} days, {d['hours']} hours, {d['minutes']} minutes, {d['seconds']} seconds\", file=stderr)"
-}
-
-## Checkers
-check_token_expiry(){
-  : '
-  Return the expiry in printable format
-  '
-  # Inputs
-  local access_token="$1"
-
-  # local vars
-  local epoch_expiry
-  local seconds_to_expiry
-
-  # Get the JWT token expiry time
-  epoch_expiry="$(get_epoch_expiry "${access_token}")"
-
-  # Compare expiry to current time
-  seconds_to_expiry="$(get_seconds_to_expiry "${epoch_expiry}")"
-
-  # Check token expiry
-  if [[ "${seconds_to_expiry}" -le 0 ]]; then
-    # Token has expired
-    echo_stderr "Error - Your access token has expired! Please refresh with 'ica-add-access-token'"
-    exit 1
-  elif [[ "${seconds_to_expiry}" -le "${SECONDS_PER_WEEK}" ]]; then
-    # Warn user token expires in less than a week
-    echo_stderr "$(warn_time_to_expiry "${seconds_to_expiry}")"
-  fi
-}
 
 check_gds(){
   : '
@@ -149,135 +32,21 @@ check_gds(){
   fi
 }
 
-check_volume(){
-  : '
-  Check volume exists
-  '
+###########ICA-ICA-LAZY SETUP ########################################
 
-  local volume_name="$1"
+if [[ -z "${ICA_ICA_LAZY_HOME-}" ]]; then
+  echo "Error - please ensure env var 'ICA_ICA_LAZY_HOME' is set" 1>&2
+  exit 1
+fi
 
-  if ! curl \
-         --silent \
-         --location \
-         --fail \
-         --request GET \
-         --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-         "${ICA_BASE_URL}/v1/volumes/${volume_name}" >/dev/null 2>&1; then
-    return 1
-  fi
-}
+if [[ -d "${ICA_ICA_LAZY_HOME}/internal-functions" ]]; then
+  for f in "${ICA_ICA_LAZY_HOME}/internal-functions/"*".sh"; do
+      # shellcheck source=../internal-functions/*.sh
+      source "$f"
+  done
+fi
 
-check_path_is_folder(){
-  : '
-  Check if the current path is a folder by first listing the folders in the parent path
-  and searching for this folder
-  '
-
-  local volume_name="$1"
-  local gds_path_attr="$2"
-  local data_params=( "--data" "volume.name=${volume_name}"
-                      "--data" "recursive=false"
-                      "--data" "pageSize=${MAX_PAGE_SIZE}" )
-
-  if [[ -n "${gds_path_attr}" && "${gds_path_attr}" != "/" ]]; then
-    data_params+=( "--data" "path=$(get_parent_path "${gds_path_attr}")*" )
-  fi
-
-  if ! folders_obj="$(curl \
-                        --silent \
-                        --location \
-                        --fail \
-                        --request GET \
-                        --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-                        --url "${ICA_BASE_URL}/v1/folders" \
-                        --get \
-                        "${data_params[@]}" 2>/dev/null)"; then
-    return 1
-  fi
-
-  if [[ "$(jq \
-            --raw-output \
-            --arg "gds_path_attr" "${gds_path_attr}" \
-            '.items[] | select ( .path == $gds_path_attr ) | .path' <<< "${folders_obj}")" != "${gds_path_attr}" ]]; then
-      return 1
-  fi
-}
-
-## Printers
-print_volumes(){
-  : '
-  Print list of volumes
-  '
-  volumes_obj="$(curl \
-                   --silent \
-                   --location \
-                   --fail \
-                   --request GET \
-                   --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-                   --url "${ICA_BASE_URL}/v1/volumes" \
-                   --get \
-                   --data "pageSize=${MAX_PAGE_SIZE}" 2>/dev/null)"
-
-    jq --raw-output \
-      '.items[] | "gds://\(.name)"' <<< "${volumes_obj}"
-}
-
-print_files_and_subfolders(){
-  : '
-  list the files and the subfolders of the path that match
-  '
-
-  local volume_name="$1"
-  local gds_path_attr="$2"
-
-  # Get folders and files
-  folders_obj="$(curl \
-                   --silent \
-                   --location \
-                   --fail \
-                   --request GET \
-                   --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-                   --url "${ICA_BASE_URL}/v1/folders" \
-                   --get \
-                   --data "volume.name=${volume_name}" \
-                   --data "recursive=false" \
-                   --data "pageSize=${MAX_PAGE_SIZE}" \
-                   --data "path=${gds_path_attr}*" 2>/dev/null)"
-
-  files_obj="$(curl \
-                 --silent \
-                 --location \
-                 --fail \
-                 --request GET \
-                 --header "Authorization: Bearer ${ICA_ACCESS_TOKEN}" \
-                 --url "${ICA_BASE_URL}/v1/files" \
-                 --get \
-                 --data "volume.name=${volume_name}" \
-                 --data "recursive=false" \
-                 --data "pageSize=${MAX_PAGE_SIZE}" \
-                 --data "path=${gds_path_attr}*" 2>/dev/null)"
-
-  # Get jq items
-  folders="$(jq \
-              --raw-output \
-              --arg "volume_name" "${volume_name}" \
-              '.items[] | "gds://\($volume_name)\(.path)"' <<< "${folders_obj}")"
-  files="$(jq \
-            --raw-output \
-            --arg "volume_name" "${volume_name}" \
-            '.items[] | "gds://\($volume_name)\(.path)"' <<< "${files_obj}")"
-
-  # Write out files and folders but sort on print
-  if [[ -z "${files}" && -z "${folders}" ]]; then
-    echo ""
-  elif [[ -z "${files}" ]]; then
-    echo "${folders}" | sort -f
-  elif [[ -z "${folders}" ]]; then
-    echo "${files}" | sort -f
-  else
-    printf "%s\n%s" "${files}" "${folders}" | sort -f
-  fi
-}
+##########END ICA-ICA-LAZY SETUP ####################################
 
 #######
 # SETUP
@@ -320,25 +89,25 @@ if ! check_gds; then
 fi
 
 # Get the volume
-volume_name="$(get_volume_name)"
+volume_name="$(get_volume_name "${gds_path}")"
 
 if [[ "${volume_name}" == "" ]]; then
-  print_volumes
+  print_volumes "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"
   exit
 fi
 
 # Check volume exists - if not print all volumes
-if ! check_volume "${volume_name}"; then
-  print_volumes
+if ! check_volume "${volume_name}" "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"; then
+  print_volumes "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"
   exit
 fi
 
 # Get the path
-gds_path_attr="$(get_path)"
+gds_path_attr="$(get_path "${gds_path}")"
 
 # Print from
-if ! check_path_is_folder "${volume_name}" "${gds_path_attr}"; then
-  print_files_and_subfolders "${volume_name}" "$(get_parent_path "${gds_path_attr}")"
+if ! check_path_is_folder "${volume_name}" "${gds_path_attr}" "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"; then
+  print_files_and_subfolders "${volume_name}" "$(get_parent_path "${gds_path_attr}")" "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"
 else
-  print_files_and_subfolders "${volume_name}" "${gds_path_attr}"
+  print_files_and_subfolders "${volume_name}" "${gds_path_attr}" "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"
 fi
diff --git a/scripts/gds-sync-download b/scripts/gds-sync-download
--- a/scripts/gds-sync-download
+++ b/scripts/gds-sync-download
@@ -56,230 +56,6 @@ binaries_check(){
   fi
 }
 
-# Check destination path
-check_download_path(){
-  local dest_path="$1"
-
-  if [[ ! -d "$(dirname "${dest_path}")" ]]; then
-    echo_stderr "Error creating \"${dest_path}\". Output paths parent must exist"
-  fi
-}
-
-# Get volume from gds path
-get_volume_from_gds_path() {
-  : '
-  Assumes urllib is available on python3
-  '
-  local gds_path="$1"
-
-  # Returns the netloc attribute of the gds_path
-  python3 -c "from urllib.parse import urlparse; print(urlparse(\"${gds_path}\").netloc)"
-}
-
-# Get folder path
-get_folder_path_from_gds_path() {
-  : '
-  Assumes urllib is available on python3
-  '
-  local gds_path="$1"
-
-  # Returns the path attribute of gds_path input
-  python3 -c "from urllib.parse import urlparse; from pathlib import Path; print(str(Path(urlparse(\"${gds_path}\").path)).rstrip(\"/\") + \"/\")"
-}
-
-get_sed_command(){
-  if [[ "${OSTYPE}" == "darwin"* ]]; then
-    echo "gsed"
-  else
-    echo "sed"
-  fi
-}
-
-get_epoch_expiry(){
-  : '
-  Get the epoch value of the expiry date of the tokens
-  '
-  local access_token="$1"
-  echo "${access_token}" | \
-    "$(get_sed_command)" -r 's/^(\S+)\.(\S+)\.(\S+)$/\2/' | \
-    ( base64 -d 2>/dev/null || true ) | \
-    jq -r '.exp'
-}
-
-get_seconds_to_expiry(){
-  : '
-  Get seconds to expiry based on epoch time
-  '
-  local expiry_epoch="$1"
-  bc <<< "${expiry_epoch} - $(date +%s)"
-}
-
-warn_time_to_expiry(){
-  : '
-  Convert the epoch time to expiry to a readable date format
-  '
-  local expiry_in_seconds="$1"
-
-  python3 -c "from datetime import timedelta; from sys import stderr; \
-              time_to_expiry=timedelta(seconds=${expiry_in_seconds}); \
-              d = {'days': time_to_expiry.days}; \
-              d['hours'], rem = divmod(time_to_expiry.seconds, 3600); \
-              d['minutes'], d['seconds'] = divmod(rem, 60); \
-              print('Expired') if ${expiry_in_seconds} < 0 \
-              else print(f\"Warning: Your ica access token will end in {d['days']} days, {d['hours']} hours, {d['minutes']} minutes, {d['seconds']} seconds\", file=stderr)"
-}
-
-check_token_expiry(){
-  : '
-  Return the expiry in printable format
-  '
-  # Inputs
-  local access_token="$1"
-
-  # local vars
-  local epoch_expiry
-  local seconds_to_expiry
-
-  # Get the JWT token expiry time
-  epoch_expiry="$(get_epoch_expiry "${access_token}")"
-
-  # Compare expiry to current time
-  seconds_to_expiry="$(get_seconds_to_expiry "${epoch_expiry}")"
-
-  # Check token expiry
-  if [[ "${seconds_to_expiry}" -le 0 ]]; then
-    # Token has expired
-    echo_stderr "Error - Your access token has expired! Please refresh with 'ica-add-access-token'"
-    exit 1
-  elif [[ "${seconds_to_expiry}" -le "${SECONDS_PER_WEEK}" ]]; then
-    # Warn user token expires in less than a week
-    echo_stderr "$(warn_time_to_expiry "${seconds_to_expiry}")"
-  fi
-}
-
-# Get folder id
-get_folder_id() {
-  : '
-  Use folders list on the folder and collect the folder id from the single item
-  '
-  local volume_name="$1"
-  local folder_path="$2"
-  local access_token="$3"
-  local base_url="$4"
-
-  # Pipe curl output into jq to collect ID and return
-  curl \
-    --silent \
-    --request GET \
-    --header "Authorization: Bearer ${access_token}" \
-    "${base_url}/v1/folders?volume.name=${volume_name}&path=${folder_path}" |
-    jq \
-      --raw-output \
-      '.items[] | .id'
-}
-
-# Get aws access creds from folder id
-get_aws_access_creds_from_folder_id() {
-  : '
-  Use folders list on the folder and collect the folder id from the single item
-  '
-  local folder_id="$1"
-  local access_token="$2"
-  local base_url="$3"
-  local aws_credentials=""
-
-  # https://ica-docs.readme.io/reference#updatefolder expects
-  # --header 'Content-Type: application/*+json'
-  # We're not actually patching anything, we're just getting some temporary credss
-  curl \
-    --silent \
-    --request PATCH \
-    --header 'Accept: application/json' \
-    --header 'Content-Type: application/*+json' \
-    --header "Authorization: Bearer ${access_token}" \
-    "${base_url}/v1/folders/${folder_id}?include=objectStoreAccess" | {
-    # We take the S3 upload creds
-    # Even though we're downloading only, aws s3 sync needs the put request param
-    jq \
-      --raw-output \
-      '.objectStoreAccess.awsS3TemporaryUploadCredentials'
-  }
-
-}
-
-# Credential get functions
-get_access_key_id_from_credentials() {
-  : '
-  Returns access_Key_id attribute
-  '
-
-  local aws_credentials="$1"
-
-  echo "${aws_credentials}" | jq --raw-output '.access_Key_Id'
-}
-
-get_secret_access_key_from_credentials() {
-  : '
-  Returns secret_Access_Key attribute
-  '
-
-  local aws_credentials="$1"
-
-  echo "${aws_credentials}" | jq --raw-output '.secret_Access_Key'
-}
-
-get_session_token_from_credentials() {
-  : '
-  Returns the session_Token attribute
-  '
-
-  local aws_credentials="$1"
-
-  echo "${aws_credentials}" | jq --raw-output '.session_Token'
-}
-
-get_region_from_credentials() {
-  : '
-  Returns the region attribute
-  '
-
-  local aws_credentials="$1"
-
-  echo "${aws_credentials}" | jq --raw-output '.region'
-
-}
-
-get_bucket_name_from_credentials() {
-  : '
-  Returns the bucketName attribute
-  '
-
-  local aws_credentials="$1"
-
-  echo "${aws_credentials}" | jq --raw-output '.bucketName'
-
-}
-
-get_key_prefix_from_credentials() {
-  : '
-  Returns the keyPrefix attribute
-  '
-
-  local aws_credentials="$1"
-
-  echo "${aws_credentials}" | jq --raw-output '.keyPrefix'
-
-}
-
-strip_path_from_base_url() {
-  : '
-  Base url should not contain any path content. We use python3 urlparse to return just the scheme and netloc.
-  '
-  local base_url="$1"
-
-  # Returns the path attribute of base_url input
-  python3 -c "from urllib.parse import urlparse; print(urlparse(\"${base_url}\").scheme + \"://\" + urlparse(\"${base_url}\").netloc)"
-}
 
 # Start main
 
@@ -289,13 +65,6 @@ gds_path=""
 download_path="$PWD"
 base_url="${ICA_BASE_URL-}"
 access_token="${ICA_ACCESS_TOKEN-}"
-
-# Check available binaries exist
-if ! binaries_check; then
-  echo_stderr "Please make sure binaries aws, jq and python3 are all available on your PATH variable"
-  print_help
-  exit 1
-fi
 
 # Get args from command line
 while [ $# -gt 0 ]; do
@@ -337,6 +106,30 @@ while [ $# -gt 0 ]; do
   esac
   shift 1
 done
+
+###########ICA-ICA-LAZY SETUP ########################################
+
+if [[ -z "${ICA_ICA_LAZY_HOME-}" ]]; then
+  echo "Error - please ensure env var 'ICA_ICA_LAZY_HOME' is set" 1>&2
+  exit 1
+fi
+
+if [[ -d "${ICA_ICA_LAZY_HOME}/internal-functions" ]]; then
+  for f in "${ICA_ICA_LAZY_HOME}/internal-functions/"*".sh"; do
+      # shellcheck source=../internal-functions/*.sh
+      source "$f"
+  done
+fi
+
+##########END ICA-ICA-LAZY SETUP ####################################
+
+
+# Check available binaries exist
+if ! binaries_check; then
+  echo_stderr "Please make sure binaries aws, jq and python3 are all available on your PATH variable"
+  print_help
+  exit 1
+fi
 
 # Strip base url
 base_url="$(strip_path_from_base_url "${base_url}")"
@@ -388,7 +181,7 @@ gds_volume="$(get_volume_from_gds_path "${gds_path}")"
 gds_folder_path="$(get_folder_path_from_gds_path "${gds_path}")"
 
 # Get the folder id
-folder_id="$(get_folder_id "${gds_volume}" "${gds_folder_path}" "${access_token}" "${base_url}")"
+folder_id="$(get_folder_id "${gds_volume}" "${gds_folder_path}" "${base_url}" "${access_token}")"
 
 # Check folder id is found
 if [[ -z "${folder_id}" || "${folder_id}" == "null" ]]; then
@@ -397,7 +190,7 @@ if [[ -z "${folder_id}" || "${folder_id}" == "null" ]]; then
 fi
 
 # Get the json aws creds with the curl PATCH command
-aws_credentials="$(get_aws_access_creds_from_folder_id "${folder_id}" "${access_token}" "${base_url}")"
+aws_credentials="$(get_aws_access_creds_from_folder_id "${folder_id}" "${base_url}" "${access_token}")"
 
 # Creds to be exported
 aws_access_key_id="$(get_access_key_id_from_credentials "${aws_credentials}")"
diff --git a/scripts/gds-task-view b/scripts/gds-task-view
--- a/scripts/gds-task-view
+++ b/scripts/gds-task-view
@@ -34,14 +34,6 @@ print_help(){
   "
 }
 
-get_docker_binary(){
-  if type docker 1>/dev/null 2>&1; then
-    echo "docker"
-  else
-    echo "podman"
-  fi
-}
-
 # Functions
 get_task_log_file(){
   : '
@@ -50,7 +42,8 @@ get_task_log_file(){
 
   local task_id="$1"
   local log_file_key="$2"
-  local access_token="$3"
+  local base_url="$3"
+  local access_token="$4"
 
   curl \
     --silent \
@@ -103,12 +96,27 @@ while [ $# -gt 0 ]; do
     shift
 done
 
+###########ICA-ICA-LAZY SETUP ########################################
+
+if [[ -z "${ICA_ICA_LAZY_HOME-}" ]]; then
+  echo "Error - please ensure env var 'ICA_ICA_LAZY_HOME' is set" 1>&2
+  exit 1
+fi
+
+if [[ -d "${ICA_ICA_LAZY_HOME}/internal-functions" ]]; then
+  for f in "${ICA_ICA_LAZY_HOME}/internal-functions/"*".sh"; do
+      # shellcheck source=../internal-functions/*.sh
+      source "$f"
+  done
+fi
+
+##########END ICA-ICA-LAZY SETUP ####################################
 
 # Get log gds path
 if [[ "${print_stdout}" == "1" ]]; then
-  log_gds_path="$(get_task_log_file "${task_id}" "stdout" "${access_token}")"
+  log_gds_path="$(get_task_log_file "${task_id}" "stdout" "${base_url}" "${access_token}")"
 elif [[ "${print_stderr}" == "1" ]]; then
-  log_gds_path="$(get_task_log_file "${task_id}" "stderr" "${access_token}")"
+  log_gds_path="$(get_task_log_file "${task_id}" "stderr" "${base_url}" "${access_token}")"
 else
   echo "Error: Please specify -o/--stdout or -e/stderr to print" 1>&2
   print_help
diff --git a/scripts/gds-view b/scripts/gds-view
--- a/scripts/gds-view
+++ b/scripts/gds-view
@@ -4,23 +4,12 @@
 Uses docker links to view the gds file through its presigned url
 '
 
+# Set to fail
 set -euo pipefail
 
-### GLOBALS
-SECONDS_PER_WEEK="604800"
-
-## Internal functions
-echo_stderr(){
-  echo "$@" 1>&2
-}
-
-get_docker_binary(){
-  if type docker 1>/dev/null 2>&1; then
-    echo "docker"
-  else
-    echo "podman"
-  fi
-}
+###########
+# FUNCTIONS
+###########
 
 print_help(){
   echo "
@@ -46,6 +35,20 @@ print_help(){
         the gds path via a presigned url.  This can be used on text files and even gzipped files!
         Use --to-stdout to print the file to stdout, or --browser to open up the file in your browser.
         "
+}
+
+run_links(){
+  : '
+  Runs the links container
+  '
+  local presigned_url="$1"
+  # Send through to links
+  "$(get_docker_binary)" run \
+    --rm \
+    -it \
+    --entrypoint "links" \
+    quay.io/umccr/alpine-links:2.21 \
+    	"${presigned_url}"
 }
 
 # Inputs
@@ -74,152 +77,21 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-###########
-# FUNCTIONS
-###########
+###########ICA-ICA-LAZY SETUP ########################################
 
-# Get volume
+if [[ -z "${ICA_ICA_LAZY_HOME-}" ]]; then
+  echo "Error - please ensure env var 'ICA_ICA_LAZY_HOME' is set" 1>&2
+  exit 1
+fi
 
-get_sed_command(){
-  if [[ "${OSTYPE}" == "darwin"* ]]; then
-    echo "gsed"
-  else
-    echo "sed"
-  fi
-}
+if [[ -d "${ICA_ICA_LAZY_HOME}/internal-functions" ]]; then
+  for f in "${ICA_ICA_LAZY_HOME}/internal-functions/"*".sh"; do
+      # shellcheck source=../internal-functions/*.sh
+      source "$f"
+  done
+fi
 
-get_epoch_expiry(){
-  : '
-  Get the epoch value of the expiry date of the tokens
-  '
-  local access_token="$1"
-  echo "${access_token}" | \
-    "$(get_sed_command)" -r 's/^(\S+)\.(\S+)\.(\S+)$/\2/' | \
-    ( base64 -d 2>/dev/null || true ) | \
-    jq -r '.exp'
-
-}
-
-get_seconds_to_expiry(){
-  : '
-  Get seconds to expiry based on epoch time
-  '
-  local expiry_epoch="$1"
-  bc <<< "${expiry_epoch} - $(date +%s)"
-}
-
-warn_time_to_expiry(){
-  : '
-  Convert the epoch time to expiry to a readable date format
-  '
-  local expiry_in_seconds="$1"
-
-  python3 -c "from datetime import timedelta; from sys import stderr; \
-              time_to_expiry=timedelta(seconds=${expiry_in_seconds}); \
-              d = {'days': time_to_expiry.days}; \
-              d['hours'], rem = divmod(time_to_expiry.seconds, 3600); \
-              d['minutes'], d['seconds'] = divmod(rem, 60); \
-              print('Expired') if ${expiry_in_seconds} < 0 \
-              else print(f\"Warning: Your ica access token will end in {d['days']} days, {d['hours']} hours, {d['minutes']} minutes, {d['seconds']} seconds\", file=stderr)"
-}
-
-## Checkers
-check_token_expiry(){
-  : '
-  Return the expiry in printable format
-  '
-  # Inputs
-  local access_token="$1"
-
-  # local vars
-  local epoch_expiry
-  local seconds_to_expiry
-
-  # Get the JWT token expiry time
-  epoch_expiry="$(get_epoch_expiry "${access_token}")"
-
-  # Compare expiry to current time
-  seconds_to_expiry="$(get_seconds_to_expiry "${epoch_expiry}")"
-
-  # Check token expiry
-  if [[ "${seconds_to_expiry}" -le 0 ]]; then
-    # Token has expired
-    echo_stderr "Error - Your access token has expired! Please refresh with 'ica-add-access-token'"
-    exit 1
-  elif [[ "${seconds_to_expiry}" -le "${SECONDS_PER_WEEK}" ]]; then
-    # Warn user token expires in less than a week
-    echo_stderr "$(warn_time_to_expiry "${seconds_to_expiry}")"
-  fi
-}
-
-get_volume_from_gds_path(){
-  : '
-  Assumes urllib is available on python3
-  '
-  local gds_path="$1"
-  # Returns the netloc attribute of the gds_path
-  python3 -c "from urllib.parse import urlparse; print(urlparse(\"${gds_path}\").netloc)"
-}
-
-# Get file path
-get_file_path_from_gds_path(){
-  : '
-  Assumes urllib is available on python3
-  '
-  local gds_path="$1"
-  # Returns the path attribute of gds_path input
-  python3 -c "from urllib.parse import urlparse; print(urlparse(\"${gds_path}\").path)"
-}
-
-get_file_id(){
-  : '
-  Use files list on the file and collect the file id from the single item
-  '
-  local volume_name="$1"
-  local file_path="$2"
-  local access_token="$3"
-  local base_url="$4"
-  # Pipe curl output into jq to collect ID and return
-  curl \
-    --silent \
-    --request GET \
-    --header "Authorization: Bearer ${access_token}" \
-    "${base_url}/v1/files?volume.name=${volume_name}&path=${file_path}" | \
-  jq \
-    --raw-output \
-    '.items[] | .id'
-}
-
-get_presigned_url_from_file_id(){
-  : '
-  Use files list on the file and collect the file id from the single item
-  '
-  local file_id="$1"
-  local access_token="$2"
-  local base_url="$3"
-  curl \
-    --silent \
-    --request GET \
-    --header "Authorization: Bearer ${access_token}" \
-    "${base_url}/v1/files/${file_id}" | \
-  jq \
-    --raw-output \
-    '.presignedUrl'
-}
-
-run_links(){
-  : '
-  Runs the links container
-  '
-  local presigned_url="$1"
-  # Send through to links
-  "$(get_docker_binary)" run \
-    --rm \
-    -it \
-    --entrypoint "links" \
-    quay.io/umccr/alpine-links:2.21 \
-    	"${presigned_url}"
-}
+##########END ICA-ICA-LAZY SETUP ####################################
 
 # Checks, ensure access_token is set
 if [[ -z "${access_token}" ]]; then
@@ -236,17 +108,15 @@ else
   check_token_expiry "${access_token}"
 fi
 
-
-
 # Get volume name / get file path from gds path
 volume_name="$(get_volume_from_gds_path "${gds_path}")"
 file_path="$(get_file_path_from_gds_path "${gds_path}")"
 
 # Collect file id
-file_id="$(get_file_id "${volume_name}" "${file_path}" "${access_token}" "${base_url}")"
+file_id="$(get_file_id "${volume_name}" "${file_path}" "${base_url}" "${access_token}")"
 
 # Collect presigned url
-presigned_url="$(get_presigned_url_from_file_id "${file_id}" "${access_token}" "${base_url}")"
+presigned_url="$(get_presigned_url_from_file_id "${file_id}" "${base_url}" "${access_token}")"
 
 # Present file
 if [[ "${to_stdout}" == "true" ]]; then
@@ -262,7 +132,7 @@ elif [[ "${browser}" == "true" ]]; then
     echo_stderr "Error: --browser selected but 'BROWSER' env var is not set"
     exit 1
   fi
-  "${BROWSER}" "${presigned_url}"
+  ${BROWSER} "${presigned_url}"
 else
   # Run links through docker
   run_links "${presigned_url}"
diff --git a/scripts/ica-add-access-token b/scripts/ica-add-access-token
--- a/scripts/ica-add-access-token
+++ b/scripts/ica-add-access-token
@@ -39,13 +39,6 @@ READ_ONLY_SCOPE_STRING="GMS.ANALYSISCONFIGURATIONS.READ,TES.TASKS.READ,GDS.FOLDE
 ###########
 
 # Standard functions
-echo_stderr(){
-  : '
-  Write to stderr
-  '
-  echo "$@" 1>&2
-}
-
 check_binaries(){
   : '
   Make sure that curl / jq / python3 pass / binary exists in PATH
@@ -63,151 +56,6 @@ check_env_vars(){
     echo_stderr "Env var ICA_BASE_URL is not set"
     return 1
   fi
-}
-
-# Get scope string based on different use cases
-get_scope_string(){
-  : '
-  Return the scopes based on the users desired access level
-  '
-  local scope_level="$1"
-  local scope
-
-  if [[ "${scope_level}" == "read-only" ]]; then
-    echo "${READ_ONLY_SCOPE_STRING}"
-  elif [[ "${scope_level}" == "admin" ]]; then
-    echo "${ADMIN_SCOPE_STRING}"
-  elif [[ "${scope_level}" == "contributor" ]]; then
-    echo "${CONTRIBUTOR_SCOPE_STRING}"
-  fi
-}
-
-# Personal access token functions
-get_default_api_key(){
-  : '
-  Gets the api key from /ica/api-keys/default-api-key in users password store
-  '
-  pass "${DEFAULT_API_KEY_STORE_PATH}" 2>/dev/null
-}
-
-create_personal_access_token(){
-  : '
-  Create a personal access token
-  '
-  local token_obj
-
-  token_obj="$(curl \
-                 --silent \
-                 --location \
-                 --fail \
-                 --request POST \
-                 --url "${ICA_BASE_URL}/v1/tokens" \
-                 --header "Accept: application/json" \
-                 --header "X-API-Key: $(get_default_api_key)" \
-                 --header "Content-Length: 0")"
-
-  # Return the access token attribute
-  jq --raw-output \
-    '.access_token' \
-    <<< "${token_obj}"
-}
-
-get_project_id_from_project_name(){
-  : '
-  Checks that the project exists from the personal context
-  and returns the project id
-  '
-
-  local project_name="$1"
-  local personal_access_token="$2"
-  local projects_list_obj
-
-  # List project objects
-  projects_list_obj="$(curl \
-                         --silent \
-                         --location \
-                         --fail \
-                         --request GET \
-                         --url "${ICA_BASE_URL}/v1/projects" \
-                         --header "Authorization: Bearer ${personal_access_token}")"
-
-  # Although we don't actually use the project id
-  project_id="$(jq --raw-output \
-                   --arg project_name "${project_name}" \
-                   '.items[] | select(.name==$project_name) | .id' \
-                   <<< "${projects_list_obj}")"
-
-  # Get the project id from the project name
-  if [[ -z "${project_id}" || "${project_id}" == "null" ]]; then
-    echo_stderr "Could not get the project id from the project name \"${project_name}\""
-    return 1
-  fi
-
-  # Return the project id
-  echo "${project_id}"
-}
-
-create_project_token(){
-  : '
-  Creates an ica access token for a given project
-  '
-  local project_id="$1"
-  local scope="$2"
-  local personal_access_token="$3"
-
-  local token_obj
-
-  token_obj="$(curl \
-                 --silent \
-                 --location \
-                 --fail \
-                 --request POST \
-                 --url "${ICA_BASE_URL}/v1/tokens" \
-                 --header "Accept: application/json" \
-                 --header "Content-Length: 0" \
-                 --header "X-API-Key: $(get_default_api_key)" \
-                 --header "Authorization: Bearer ${personal_access_token}" \
-                 --get \
-                 --data "cid=${project_id}" \
-                 --data "scopes=$(get_scope_string "${scope}")")"
-
-  # Return the access token attribute
-  jq --raw-output \
-    '.access_token' \
-    <<< "${token_obj}"
-}
-
-add_token_to_json_file(){
-  : '
-  Adds the token to the json file
-  '
-  local project_name="$1"
-  local scope="$2"
-  local project_access_token="$3"
-
-  # Get directory
-  mkdir -p "$(dirname "${TOKEN_FILE_PATH}")"
-  chmod 700 "$(dirname "${TOKEN_FILE_PATH}")"
-
-  if [[ ! -f "${TOKEN_FILE_PATH}" ]]; then
-    in_json="{}"
-  else
-    in_json="$(cat "${TOKEN_FILE_PATH}")"
-  fi
-
-  # Import file and add to list
-  tokens_obj="$(jq \
-                  --raw-output \
-                  --arg project_name "${project_name}" \
-                  --arg scope "${scope}" \
-                  --arg project_access_token "${project_access_token}" \
-                  '.[$project_name][$scope] = $project_access_token' <<< "${in_json}")"
-
-  # Write token object back out to file
-  echo "${tokens_obj}" > "${TOKEN_FILE_PATH}"
-
-  # Change permissions on file
-  chmod 600 "${TOKEN_FILE_PATH}"
 }
 
 print_help(){
@@ -258,6 +106,22 @@ while [ $# -gt 0 ]; do
   shift 1
 done
 
+###########ICA-ICA-LAZY SETUP ########################################
+
+if [[ -z "${ICA_ICA_LAZY_HOME-}" ]]; then
+  echo "Error - please ensure env var 'ICA_ICA_LAZY_HOME' is set" 1>&2
+  exit 1
+fi
+
+if [[ -d "${ICA_ICA_LAZY_HOME}/internal-functions" ]]; then
+  for f in "${ICA_ICA_LAZY_HOME}/internal-functions/"*".sh"; do
+      # shellcheck source=../internal-functions/*.sh
+      source "$f"
+  done
+fi
+
+##########END ICA-ICA-LAZY SETUP ####################################
+
 # Check args
 if [[ -z "${project_name-}" ]]; then
   echo_stderr "Error: --project-name not defined"
@@ -303,7 +167,7 @@ fi
 # CREATE PERSONAL PAT
 #####################
 echo_stderr "Creating a personal access token"
-personal_access_token="$(create_personal_access_token)"
+personal_access_token="$(create_personal_access_token "${ICA_BASE_URL}")"
 # Check personal token
 if [[ -z "${personal_access_token}" || "${personal_access_token}" == "null" ]]; then
   echo_stderr "Error: Could not create a personal access token"
@@ -325,7 +189,7 @@ fi
 # CREATE PROJECT TOKEN
 ######################
 echo_stderr "Creating project token"
-project_access_token="$(create_project_token "${project_id}" "${scope}" "${personal_access_token}")"
+project_access_token="$(create_project_token "${project_id}" "${scope}" "${ICA_BASE_URL}" "${personal_access_token}")"
 # Check project token
 if [[ -z "${project_access_token}" || "${project_access_token}" == "null" ]]; then
   echo_stderr "Error: Could not create a project access token"
diff --git a/scripts/ica-check-cwl-inputs b/scripts/ica-check-cwl-inputs
--- a/scripts/ica-check-cwl-inputs
+++ b/scripts/ica-check-cwl-inputs
@@ -6,507 +6,8 @@ Given an input json checks the following
 input is present
 name is present
 check if engineParameters is present - encourage user to use if not present
-
-Much credit to this snippet for flattening arrays in jq
-https://gist.github.com/olih/f7437fb6962fb3ee9fe95bda8d2c8fa4#gistcomment-3045352
 '
 
-### GLOBALS
-SECONDS_PER_WEEK="604800"
-
-echo_stderr(){
-  echo "${@}" 1>&2
-}
-
-flatten_inputs(){
-  : '
-  Get the flattened inputs object as a . based flattened output
-  '
-  jq --raw-output '[
-         . as $in |
-         (paths(scalars), paths((. | length == 0)?)) |
-         join(".") as $key |
-         $key + "=" + ($in | getpath($key | split(".") | map((. | tonumber)? // .)) | tostring)
-       ] |
-       sort |
-       .[]' <<< "$1"
-}
-
-get_sed_command(){
-  if [[ "${OSTYPE}" == "darwin"* ]]; then
-    echo "gsed"
-  else
-    echo "sed"
-  fi
-}
-
-get_epoch_expiry(){
-  : '
-  Get the epoch value of the expiry date of the tokens
-  '
-  local access_token="$1"
-  echo "${access_token}" | \
-    "$(get_sed_command)" -r 's/^(\S+)\.(\S+)\.(\S+)$/\2/' | \
-    ( base64 -d 2>/dev/null || true ) | \
-    jq -r '.exp'
-}
-
-get_seconds_to_expiry(){
-  : '
-  Get seconds to expiry based on epoch time
-  '
-  local expiry_epoch="$1"
-  bc <<< "${expiry_epoch} - $(date +%s)"
-}
-
-warn_time_to_expiry(){
-  : '
-  Convert the epoch time to expiry to a readable date format
-  '
-  local expiry_in_seconds="$1"
-
-  python3 -c "from datetime import timedelta; from sys import stderr; \
-              time_to_expiry=timedelta(seconds=${expiry_in_seconds}); \
-              d = {'days': time_to_expiry.days}; \
-              d['hours'], rem = divmod(time_to_expiry.seconds, 3600); \
-              d['minutes'], d['seconds'] = divmod(rem, 60); \
-              print('Expired') if ${expiry_in_seconds} < 0 \
-              else print(f\"Warning: Your ica access token will end in {d['days']} days, {d['hours']} hours, {d['minutes']} minutes, {d['seconds']} seconds\", file=stderr)"
-}
-
-## Checkers
-check_token_expiry(){
-  : '
-  Return the expiry in printable format
-  '
-  # Inputs
-  local access_token="$1"
-
-  # local vars
-  local epoch_expiry
-  local seconds_to_expiry
-
-  # Get the JWT token expiry time
-  epoch_expiry="$(get_epoch_expiry "${access_token}")"
-
-  # Compare expiry to current time
-  seconds_to_expiry="$(get_seconds_to_expiry "${epoch_expiry}")"
-
-  # Check token expiry
-  if [[ "${seconds_to_expiry}" -le 0 ]]; then
-    # Token has expired
-    echo_stderr "Error - Your access token has expired! Please refresh with 'ica-add-access-token'"
-    exit 1
-  elif [[ "${seconds_to_expiry}" -le "${SECONDS_PER_WEEK}" ]]; then
-    # Warn user token expires in less than a week
-    echo_stderr "$(warn_time_to_expiry "${seconds_to_expiry}")"
-  fi
-}
-
-get_definition_from_ica(){
-  : '
-  Use curl to pull down the packed cwl defintion of the workflow
-  '
-
-  local ica_workflow_id="$1"
-  local ica_workflow_version_name="$2"
-  local ica_base_url="$3"
-  local ica_access_token="$4"
-  curl \
-    --silent \
-    --request GET \
-    --header "Authorization: Bearer ${ica_access_token}" \
-    "${ica_base_url}/v1/workflows/${ica_workflow_id}/versions/${ica_workflow_version_name}" |
-  jq \
-    --raw-output \
-    '.definition | fromjson'
-}
-
-get_inputs_from_cwl_definition(){
-  : '
-    Get the inputs objects from the cwl definition object
-    First we split by type packed workflows use graphs and
-    have the inputs in the last element of the graph array
-    commandlinetools just have the inputs in the top key
-    we then strip out the "#" from the id.
-    if the "id" is not set on the on the cwltool it will have a "main/" prefix, which we strip out
-  '
-
-  local packed_cwl_definition="$1"
-
-  jq --raw-output '(
-         if (.["$graph"] | length) !=0 then
-             .["$graph"][-1]
-         else
-             .
-         end) |
-         .inputs[]' <<< "${packed_cwl_definition}"
-}
-
-get_input_block_from_input_name(){
-  : '
-  Get the input chunk from the input name - matches on id
-  '
-  # Get inputs
-  local input_name="$1"
-  local input_json="$2"
-
-  jq --raw-output \
-    --arg input_name "${input_name}" \
-    'select(.id == ("#" + $input_name) or .id == ("#/main" + $input_name))' <<< "${input_json}"
-}
-
-is_input_required(){
-  : '
-  Given an input chunk, determine it is required
-  echo "false" if not required
-  echo "true" if required
-  '
-  # Get inputs
-  local input_chunk="$1"
-
-  # Input is optional if type attribute is an array and "null" is in the type array
-  jq --raw-output \
-      'if ((.type | type == "array") and (.type | any("null"))) then
-          "false"
-      else
-          "true"
-      end' <<< "${input_chunk}"
-}
-
-get_id_from_input_chunk(){
-  : '
-  Given an input collect the id and remove the "#" and the "/main" attributes
-  '
-  local input_chunk="$1"
-
-  jq --raw-output \
-    '.id | sub("^#"; "") | sub("^main/"; "")' <<< "${input_chunk}"
-
-}
-
-get_required_inputs_list(){
-  : '
-  Get a chunk of inputs that are required for the workflow
-  '
-
-  # Use nameref
-  local -n temp_required_inputs_array="$1"
-  local input_json="$2"
-  local input_chunks_array
-  local input_id
-
-  readarray -t input_chunks_array < <(jq --raw-output --compact-output <<< "${input_json}")
-
-  # Iterate over the input ids, if input is required, then append the id to true
-  for input_chunk in "${input_chunks_array[@]}"; do
-    input_id="$(get_id_from_input_chunk "${input_chunk}")"
-    if [[ "$(is_input_required "${input_chunk}")" == "true" ]]; then
-      temp_required_inputs_array+=("${input_id}")
-    fi
-  done
-}
-
-get_sed_command(){
-  if [[ "${OSTYPE}" == "darwin"* ]]; then
-    echo "gsed"
-  else
-    echo "sed"
-  fi
-}
-
-# Get volume from gds path
-get_volume_from_gds_path() {
-  : '
-  Assumes urllib is available on python3
-  '
-  local gds_path="$1"
-
-  # Returns the netloc attribute of the gds_path
-  python3 -c "from urllib.parse import urlparse; print(urlparse(\"${gds_path}\").netloc)"
-}
-
-# Get folder path
-get_folder_path_from_gds_path() {
-  : '
-  Assumes urllib is available on python3
-  '
-  local gds_path="$1"
-
-  # Returns the path attribute of gds_path input
-  python3 -c "from urllib.parse import urlparse; from pathlib import Path; print(str(Path(urlparse(\"${gds_path}\").path)).rstrip(\"/\") + \"/\")"
-}
-
-get_file_path_from_gds_path(){
-  : '
-  Assumes urllib is available on python3
-  '
-  local gds_path="$1"
-  # Returns the path attribute of gds_path input
-  python3 -c "from urllib.parse import urlparse; print(urlparse(\"${gds_path}\").path)"
-}
-
-
-check_folder_exists(){
-  : '
-  Check that the input folder exists
-  folder checking is a little more complex than file checking, need to run an ica folders list on the folder itself and
-  then get the folder id
-  # TODO - test this bit
-  '
-  local input_key_stripped="$1"
-  local input_value="$2"
-  local ica_access_token="$3"
-  local ica_base_url="$4"
-  local volume_name
-  local folder_path
-
-  volume_name="$(get_volume_from_gds_path "${input_value}")"
-  folder_path="$(get_folder_path_from_gds_path "${input_value}")"
-
-  # Return the folder id
-  folder_id="$(curl \
-                 --silent \
-                 --request GET \
-                 --header "Authorization: Bearer ${ica_access_token}" \
-                 "${ica_base_url}/v1/folders?volume.name=${volume_name}&path=${folder_path}" |
-               jq \
-                 --raw-output \
-                 '.items[] | .id')"
-
-  if [[ -z "${folder_id}" || "${folder_id}" == "null" ]]; then
-    echo_stderr "Could not get folder id for \"${input_value}\""
-    return 1
-  fi
-}
-
-check_file_exists(){
-  : '
-  Check that the input file exists
-  '
-  local input_key_stripped="$1"
-  local input_value="$2"
-  local ica_access_token="$3"
-  local ica_base_url="$4"
-  local volume_name
-  local file_path
-
-  volume_name="$(get_volume_from_gds_path "${input_value}")"
-  file_path="$(get_file_path_from_gds_path "${input_value}")"
-
-  # Return the folder id
-  file_id="$(curl \
-                 --silent \
-                 --request GET \
-                 --header "Authorization: Bearer ${ica_access_token}" \
-                 "${ica_base_url}/v1/files?volume.name=${volume_name}&path=${file_path}" |
-               jq \
-                 --raw-output \
-                 '.items[] | .id')"
-
-  if [[ -z "${file_id}" || "${file_id}" == "null" ]]; then
-    echo_stderr "Could not get file id for \"${input_value}\""
-    return 1
-  fi
-}
-
-get_class_type(){
-  : '
-  Get the class type, iterate over flattened inputs, get value of "input_key_stripped"."class"
-  '
-  local input_key_stripped="$1"
-  local flattened_inputs="$2"
-
-  while read -r input_key_val_pair; do
-     # Split into keys and values
-     input_key="$(cut -d'=' -f1 <<< "${input_key_val_pair}")"
-     input_value="$(cut -d'=' -f2 <<< "${input_key_val_pair}")"
-
-     # Get the input value
-     if [[ "${input_key}" == "${input_key_stripped}.class" ]]; then
-       if [[ "${input_value,,}" == "file"  || "${input_value,,}" == "directory" ]]; then
-         # ,, syntax means .tolower()
-         echo "gds_${input_value,,}"
-       fi
-     fi
-  done <<< "${flattened_inputs}"
-}
-
-strip_first_period(){
-  : '
-  Equivalent of split(".", 1)[0] in python
-  '
-  local input_key="$1"
-  cut -d'.' -f1 <<< "${input_key}"
-}
-
-strip_last_period(){
-  : '
-  Equivalent of rsplit(".", 1)[0] in python
-  '
-  local input_key="$1"
-  # This is gross, I am sorry
-  # sed is greedy, so the first (.*) will match as much as it can
-  "$(get_sed_command)" -r "s/(.*)\.(.*)/\1/" <<< "${input_key}"
-}
-
-delete_item_from_array(){
-  : '
-  Delete an item from array
-  '
-  local -n input_array="$1"
-  local input_value="$2"
-  local input_del_array=( "${input_value}" )
-
-  for target in "${input_del_array[@]}"; do
-    for i in "${!input_array[@]}"; do
-      if [[ "${input_array[${i}]}" == "${target}" ]]; then
-        unset "input_array[${i}]"
-      fi
-    done
-  done
-}
-
-check_name_value(){
-  : '
-  Check name value
-  '
-  local name_value="$1"
-
-  if [[ "${name_value}" =~ [^a-zA-Z0-9_-\.] ]]; then
-    echo_stderr "Name must be a-zA-Z0-9_-, please don't put in spaces or symbols"
-    return 1
-  fi
-}
-
-check_input_paths_and_locations(){
-  : '
-  Iterate through inputs, make sure each gds path exists in this context
-  '
-  local flattened_inputs="$1"
-  local ica_workflow_inputs="$2"
-  local ica_base_url="$3"
-  local ica_access_token="$4"
-  local original_required_inputs_array_length
-  local all_there=0  # Is everything present?
-  local input_key
-  local input_key_lstripped
-  local input_key_rstripped
-  local input_value
-  local input_block
-  # Assigned in get_required_inputs_list
-  # Uses some nameref magic as shown here: https://stackoverflow.com/questions/10582763/how-to-return-an-array-in-bash-without-using-globals
-  local required_inputs_array
-
-  # Get required array
-  if [[ -n "${ica_workflow_inputs}" ]]; then
-    get_required_inputs_list required_inputs_array "${ica_workflow_inputs}"
-    original_required_inputs_array_length="${#required_inputs_array[@]}"
-  fi
-
-  echo_stderr "Ensuring that all required inputs are present: " "${required_inputs_array[@]}"
-
-  # Iterate through key val pairs
-  # Like tumor_fastq_list_rows.0.read_1.location=gds://...
-  while read -r input_key_val_pair; do
-     # Split into keys and values
-     input_key="$(cut -d'=' -f1 <<< "${input_key_val_pair}")"
-     # Stripp input key to just get first elmeent umccrise_tsv_rows.0.sv_vcf.path to umccrise_tsv_rows
-     input_key_lstripped="$(strip_first_period "${input_key}")"
-     # Stripped input key umccrise_tsv_rows.0.sv_vcf.path to just umccrise_tsv_rows.0.sv_vcf
-     input_key_rstripped="$(strip_last_period "${input_key}")"
-     input_value="$(cut -d'=' -f2 <<< "${input_key_val_pair}")"
-
-     # Check if is part of the inputs?
-     if [[ -n "${ica_workflow_inputs}" ]]; then
-       input_block="$(get_input_block_from_input_name "${input_key_lstripped}" "${ica_workflow_inputs}")"
-
-       # Check input block is present
-       if [[ -z "${input_block}" ]]; then
-         echo_stderr "Error! '${input_key}' is not a recognised input of the workflow"
-         all_there=1
-       fi
-
-       # Remove an element from the array
-       # As shown here: https://stackoverflow.com/questions/16860877/remove-an-element-from-a-bash-array
-       delete_item_from_array required_inputs_array "${input_key_lstripped}"
-     fi
-
-     # Check if the input-key ends in .path or .location
-     if [[ "${input_key}" =~ .*\.path || "${input_key}" =~ .*\.location ]]; then
-       # Get class type
-       class_type="$(get_class_type "${input_key_rstripped}" "${flattened_inputs}")"
-
-       # If a directory, make sure it exists
-       if [[ "${class_type}" == "gds_directory" ]]; then
-         echo_stderr "Input '${input_key}' is a gds directory at '${input_value}', checking it's present."
-         if ! check_folder_exists "${input_key_rstripped}" "${input_value}" "${ica_access_token}" "${ica_base_url}"; then
-           echo_stderr "Error! Could not find gds directory '${input_value}' for input '${input_key_rstripped}'"
-           all_there=1
-         fi
-       # If a file, make sure it exists
-       elif [[ "${class_type}" == "gds_file" ]]; then
-        echo_stderr "Input '${input_key}' is a gds file at '${input_value}' checking it's present."
-         if ! check_file_exists "${input_key_rstripped}" "${input_value}" "${ica_access_token}" "${ica_base_url}"; then
-           echo_stderr "Error! Could not find gds file '${input_value}' for input '${input_key_rstripped}'"
-           all_there=1
-         fi
-       fi
-     fi
-  done <<< "${flattened_inputs}"
-
-  # Get length of the required input array
-  if [[ -n "${ica_workflow_inputs}" && "${original_required_inputs_array_length}" != 0 && "${#required_inputs_array[@]}" != "0" ]]; then
-    echo_stderr "Error! Some required inputs are not satisfied"
-    echo_stderr "Error! The following inputs could not be found in the input.json: " "${required_inputs_array[@]}"
-    return 1
-  fi
-
-  # Return 1 if not all inputs are present on gds otherwise return 0
-  if [[ "${all_there}" == 1 ]]; then
-    return 1
-  else
-    return 0
-  fi
-}
-
-
-check_input_value(){
-  : '
-  Check input value
-  '
-  local inputs="$1"
-  local ica_workflow_inputs="$2"
-  local ica_base_url="$3"
-  local ica_access_token="$4"
-
-  # Check if inputs are null
-  if [[ -z "${inputs}" || "${inputs}" == "null" ]]; then
-    echo_stderr "Could not find any inputs, under 'input'. Are you sure you want this?"
-    return 0
-  fi
-
-  # Flatten input json into .dot format
-  flattened_inputs="$(flatten_inputs "${inputs}")"
-
-  # Check paths are present on gds and match input ids in definition on ICA if ica_workflow_inputs is defined
-  check_input_paths_and_locations "${flattened_inputs}" "${ica_workflow_inputs}" "${ica_base_url}" "${ica_access_token}"
-}
-
-check_engine_parameters(){
-  : '
-  Check the engine parameters
-  '
-  local engine_parameters="$1"
-
-  # Check if inputs are null
-  if [[ -z "${engine_parameters}" || "${engine_parameters}" == "null" || "$(jq 'keys | length' <<< "${engine_parameters}")" == "0" ]]; then
-    echo_stderr "Could not find any engine parameters, under 'engineParameters'"
-    echo_stderr "For future runs, I would recommend setting outputDirectory and workDirectory."
-  fi
-
-  return 0
-}
 
 print_help(){
   echo "
@@ -568,6 +69,23 @@ while [ $# -gt 0 ]; do
   esac
   shift 1
 done
+
+###########ICA-ICA-LAZY SETUP ########################################
+
+if [[ -z "${ICA_ICA_LAZY_HOME-}" ]]; then
+  echo "Error - please ensure env var 'ICA_ICA_LAZY_HOME' is set" 1>&2
+  exit 1
+fi
+
+if [[ -d "${ICA_ICA_LAZY_HOME}/internal-functions" ]]; then
+  for f in "${ICA_ICA_LAZY_HOME}/internal-functions/"*".sh"; do
+      # shellcheck source=../internal-functions/*.sh
+      source "$f"
+  done
+fi
+
+##########END ICA-ICA-LAZY SETUP ####################################
+
 
 # Check ICA_BASE_URL env var is set
 if [[ -z "${ICA_BASE_URL-}" ]]; then
diff --git a/scripts/ica-illumination b/scripts/ica-illumination
--- a/scripts/ica-illumination
+++ b/scripts/ica-illumination
@@ -11,12 +11,6 @@ set -euo pipefail
 #########
 DEFAULT_PORT="3000"
 DEFAULT_SCOPE="read-only"
-TOKENS_PATH="$HOME/.ica-ica-lazy/tokens/tokens.json"
-SECONDS_PER_WEEK="604800"
-
-echo_stderr(){
-  echo "$@" 1>&2
-}
 
 print_help(){
   echo "
@@ -36,145 +30,11 @@ print_help(){
   "
 }
 
-get_sed_command(){
-  if [[ "${OSTYPE}" == "darwin"* ]]; then
-    echo "gsed"
-  else
-    echo "sed"
-  fi
-}
-
-get_docker_binary(){
-  if type docker 1>/dev/null 2>&1; then
-    echo "docker"
-  else
-    echo "podman"
-  fi
-}
-
-get_epoch_expiry(){
-  : '
-  Get the epoch value of the expiry date of the tokens
-  '
-  local access_token="$1"
-
-  echo "${access_token}" | \
-    "$(get_sed_command)" -r 's/^(\S+)\.(\S+)\.(\S+)$/\2/' | \
-    ( base64 \
-        --decode 2>/dev/null || true ) | \
-    jq -r '.exp'
-}
-
-get_seconds_to_expiry(){
-  : '
-  Get seconds to expiry based on epoch time
-  '
-  local expiry_epoch="$1"
-  bc <<< "${expiry_epoch} - $(date +%s)"
-}
-
-check_port_not_in_use(){
-  : '
-  Check port not in use
-  '
-
-  # Check port doesn't have an existing container running on it
-  iterable=0
-  max_iterable=10
-
-  while :; do
-    # Don't go through an infinite loop!
-    iterable=$(("${iterable}" + 1))
-    if [[ "${iterable}" -ge "${max_iterable}" ]]; then
-      echo_stderr "Tried 10 ports, all of them are full!"
-      exit 1
-    fi
-
-    # Check if port is in use - podman doesn't support the --publish filter
-    if [[ "$(get_docker_binary)" == "docker" && "$(docker ps --filter publish="${port}" --quiet | wc -l)" == 0 ]]; then
-      # Port not in use!
-      break
-    elif [[ "$(get_docker_binary)" == "podman" && "$(podman ps --format "{{.Ports}}" | sed -r 's%^[0-9|\.]+\:([0-9]+)->[0-9]+\/tcp$%\1%' | grep -c "^${port}$")" == 0 ]]; then
-      # Port not in use!
-      break
-    fi
-
-    # Iterate port by one
-    echo_stderr "Port ${port} in use, trying $(("${port}" + 1))"
-    port="$(("${port}" + 1))"
-  done
-
-  echo "${port}"
-}
-
-warn_time_to_expiry(){
-  : '
-  Convert the epoch time to expiry to a readable date format
-  '
-  local expiry_in_seconds="$1"
-
-  python3 -c "from datetime import timedelta; from sys import stderr; \
-              time_to_expiry=timedelta(seconds=${expiry_in_seconds}); \
-              d = {'days': time_to_expiry.days}; \
-              d['hours'], rem = divmod(time_to_expiry.seconds, 3600); \
-              d['minutes'], d['seconds'] = divmod(rem, 60); \
-              print('Expired') if ${expiry_in_seconds} < 0 \
-              else print(f\"Warning: Your ica access token will end in {d['days']} days, {d['hours']} hours, {d['minutes']} minutes, {d['seconds']} seconds\", file=stderr)"
-}
-
-## Checkers
-check_token_expiry(){
-  : '
-  Return the expiry in printable format
-  '
-  # Inputs
-  local access_token="$1"
-
-  # local vars
-  local epoch_expiry
-  local seconds_to_expiry
-
-  # Get the JWT token expiry time
-  epoch_expiry="$(get_epoch_expiry "${access_token}")"
-
-  # Compare expiry to current time
-  seconds_to_expiry="$(get_seconds_to_expiry "${epoch_expiry}")"
-
-  # Check token expiry
-  if [[ "${seconds_to_expiry}" -le 0 ]]; then
-    # Token has expired
-    echo_stderr "Error - Your access token has expired! Please refresh with 'ica-add-access-token'"
-    exit 1
-  elif [[ "${seconds_to_expiry}" -le "${SECONDS_PER_WEEK}" ]]; then
-    # Warn user token expires in less than a week
-    echo_stderr "$(warn_time_to_expiry "${seconds_to_expiry}")"
-  fi
-}
-
-get_access_token(){
-  : '
-  Check the level of the scope
-  '
-  # Func inputs
-  local project_name="$1"
-  local scope="$2"
-  local tokens_file_path="$3"
-  local in_json
-  local project_access_token
-  in_json="$(cat "${tokens_file_path}")"
-  project_access_token="$(jq \
-                            --raw-output \
-                            --arg project_name "${project_name}" \
-                            --arg scope "${scope}" \
-                          '.[$project_name][$scope]' <<< "${in_json}")"
-  echo "${project_access_token}"
-}
-
 check_binaries(){
   : '
   Make sure that jq / docker binaries exists in PATH
   '
-  if ! (type "$(get_docker_binary)" jq "${sed_binary}" 1>/dev/null); then
+  if ! (type "$(get_docker_binary)" jq "$(get_sed_binary)" 1>/dev/null); then
     return 1
   fi
 }
@@ -219,12 +79,21 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-# Get sed binary
-if [[ "${OSTYPE}" == "darwin" ]]; then
-  sed_binary="gsed"
-else
-  sed_binary="sed"
+###########ICA-ICA-LAZY SETUP ########################################
+
+if [[ -z "${ICA_ICA_LAZY_HOME-}" ]]; then
+  echo "Error - please ensure env var 'ICA_ICA_LAZY_HOME' is set" 1>&2
+  exit 1
 fi
+
+if [[ -d "${ICA_ICA_LAZY_HOME}/internal-functions" ]]; then
+  for f in "${ICA_ICA_LAZY_HOME}/internal-functions/"*".sh"; do
+      # shellcheck source=../internal-functions/*.sh
+      source "$f"
+  done
+fi
+
+##########END ICA-ICA-LAZY SETUP ####################################
 
 # Check binaries
 if ! check_binaries; then
@@ -240,17 +109,17 @@ if [[ -z "${project_name-}" ]]; then
 fi
 
 # Check project name in TOKENS PATH
-if [[ -z "$(jq --raw-output --arg project "${project_name}" 'select(.[$project] != null) | .[$project] | keys' <<< cat "${TOKENS_PATH}")" ]]; then
+if [[ -z "$(jq --raw-output --arg project "${project_name}" 'select(.[$project] != null) | .[$project] | keys' <<< cat "$(get_tokens_path "${ICA_ICA_LAZY_HOME}")")" ]]; then
   echo_stderr "Error: Could not get project '${project_name}' from tokens path"
   exit 1
 fi
 
 # Get access token
-project_access_token="$(get_access_token "${project_name}" "${DEFAULT_SCOPE}" "${TOKENS_PATH}")"
+project_access_token="$(get_access_token "${project_name}" "${DEFAULT_SCOPE}" "$(get_tokens_path "${ICA_ICA_LAZY_HOME}")")"
 
 # Try admin scope
 if [[ -z "${project_access_token}" || "${project_access_token}" == "null" ]]; then
-  project_access_token="$(get_access_token "${project_name}" "admin" "${TOKENS_PATH}")"
+  project_access_token="$(get_access_token "${project_name}" "admin" "$(get_tokens_path "${ICA_ICA_LAZY_HOME}")")"
 fi
 
 
@@ -283,11 +152,11 @@ fi
 echo_stderr "Docker launched Illumination successfully"
 echo_stderr "Please head to localhost://${port} on your preferred browser"
 
-docker_name="$("$(get_docker_binary)" container inspect "${docker_id}" | jq --raw-output '.[0].Name' | "${sed_binary}" 's%^\/%%')"
+docker_name="$("$(get_docker_binary)" container inspect "${docker_id}" | jq --raw-output '.[0].Name' | "$(get_sed_binary)" 's%^\/%%')"
 
 echo_stderr "To stop the container, please run '$(get_docker_binary) kill \"${docker_name}\"'"
 
-if [[ -n "${BROWSER}" ]]; then
+if [[ -n "${BROWSER-}" ]]; then
   echo_stderr "${BROWSER} environment variable is set. Opening up 'localhost://${port}'"
-  "${BROWSER}" "http://localhost:${port}"
+  ${BROWSER} "http://localhost:${port}"
 fi
