Sync scripts update:
* Better handling on unbound variables
* Use a debug trap to capture the sync command and return code, good for error handling for user
* Scripts were showing complete even if return code was non-zero
* Download script no longer prints 'Upload complete'

diff --git a/scripts/gds-sync-upload b/scripts/gds-sync-upload
--- a/scripts/gds-sync-upload
+++ b/scripts/gds-sync-upload
@@ -242,7 +242,7 @@ aws_s3_sync_args=()
 gds_path=""
 src_path="$PWD"
 base_url="${ICA_BASE_URL}"
-access_token="${ICA_ACCESS_TOKEN}"
+access_token="${ICA_ACCESS_TOKEN-}"
 
 # Check available binaries exist
 if ! binaries_check; then
@@ -290,15 +290,16 @@ done
 
 # Check mandatory args are defined
 if [[ -z "${gds_path}" ]]; then
-  echo_stderr "Please set --gds-path"
+  echo_stderr "Error: Please set --gds-path"
   print_help
   exit 1
 elif [[ -z "${access_token}" ]]; then
-  echo_stderr "Please set the env var ICA_ACCESS_TOKEN"
+  echo_stderr "Error: Please set the env var ICA_ACCESS_TOKEN"
+  echo_stderr "Error: Please first run ica-context-switcher"
   print_help
   exit 1
 elif [[ -z "${base_url}" ]]; then
-  echo_stderr "Please set the env var ICA_BASE_URL"
+  echo_stderr "Error: Please set the env var ICA_BASE_URL"
   print_help
   exit 1
 fi
@@ -363,6 +364,20 @@ export AWS_ACCESS_KEY_ID="${aws_access_key_id}"
 export AWS_SECRET_ACCESS_KEY="${aws_secret_access_key}"
 export AWS_SESSION_TOKEN="${aws_session_token}"
 export AWS_DEFAULT_REGION="${aws_default_region}"
-eval aws s3 sync "${src_path}" "s3://${aws_bucket_name}/${aws_key_prefix}" '"${aws_s3_sync_args[@]}"'
 
-echo_stderr "Upload complete"
+# Use trap to catch the command to debug
+trap 'previous_command=$this_command; this_command=$BASH_COMMAND' DEBUG
+# Launch through eval to expand sync arguments
+if eval aws s3 sync "${src_path}" "s3://${aws_bucket_name}/${aws_key_prefix}" '"${aws_s3_sync_args[@]}"'; then
+  echo_stderr "Upload complete!"
+else
+  # Get command and return code of aws s3 sync
+  s3_command="${previous_command}" non_zero_exit_code="$?"
+  # Get S3 command as an array
+  IFS=' ' read -r -a s3_command_array <<< "${s3_command}"
+  # Drop aws_s3_sync_args
+  unset s3_command_array["-1"]
+  echo_stderr "Error: Sync command failed with exit code ${non_zero_exit_code}. Sync command was '${s3_command_array[*]} ${aws_s3_sync_args[*]}'"
+  # Exit with same failure
+  exit "${non_zero_exit_code}"
+fi
