gds-view and gds-task-view now include --to-stdout parameter

diff --git a/scripts/gds-task-view b/scripts/gds-task-view
--- a/scripts/gds-task-view
+++ b/scripts/gds-task-view
@@ -18,11 +18,13 @@ print_help(){
             -g / --task-run-id: Path to gds file
             -o / --stdout: Shows the task stdout
             -e / --stderr: Shows the task stderr
+            -s / --to-stdout: Print file to stdout
 
         Requirements:
           * docker
           * jq
           * python3
+          * wget
 
         Environment:
           * ICA_BASE_URL
@@ -59,6 +61,7 @@ get_task_log_file(){
 task_id=""
 base_url="${ICA_BASE_URL-}"
 access_token="${ICA_ACCESS_TOKEN-}"
+to_stdout="false"
 print_stdout=0
 print_stderr=0
 log_gds_path=""
@@ -75,6 +78,9 @@ while [ $# -gt 0 ]; do
         ;;
         -e|--stderr)
             print_stderr="1"
+        ;;
+        -s|--to-stdout)
+            to_stdout="true"
         ;;
         -h|--help)
             print_help
@@ -95,15 +101,23 @@ else
   exit 1
 fi
 
-  # Checks, ensure access_token is set
+# Checks, ensure access_token is set
 if [[ -z "${access_token}" ]]; then
   echo "Error: Need to set ICA_ACCESS_TOKEN env var" 1>&2
+  echo "Error: Please first run ica-context-switcher" 1>&2
   print_help
   exit 1
+fi
+
+# Stdout param
+if [[ "${to_stdout}" == "true" ]]; then
+  stdout_param="--to-stdout"
+else
+  stdout_param=""
 fi
 
 # Run ica_view
 ICA_ACCESS_TOKEN="${access_token}" \
 ICA_BASE_URL="${base_url}" \
    gds-view \
-    --gds-path "${log_gds_path}"
+    --gds-path "${log_gds_path}" "${stdout_param}"
diff --git a/scripts/gds-view b/scripts/gds-view
--- a/scripts/gds-view
+++ b/scripts/gds-view
@@ -12,11 +12,13 @@ print_help(){
 
         Options:
             -g / --gds-path: Path to gds file
+            -s / --to-stdout: Print file to stdout
 
         Requirements:
           * docker
           * jq
           * python3
+          * wget
 
         Environment:
           * ICA_BASE_URL
@@ -31,12 +33,16 @@ print_help(){
 gds_path=""
 access_token="${ICA_ACCESS_TOKEN-}"
 base_url="${ICA_BASE_URL-}"
+to_stdout="false"
 
 while [ $# -gt 0 ]; do
     case "$1" in
         -g|--gds-path)
             gds_path="$2"
             shift 1
+        ;;
+        -s|--to-stdout)
+            to_stdout="true"
         ;;
         -h|--help)
             print_help
@@ -122,10 +128,11 @@ run_links(){
 # Checks, ensure access_token is set
 if [[ -z "${access_token}" ]]; then
   echo "Error: Need to set ICA_ACCESS_TOKEN env var" 1>&2
+  echo "Error: Please first run ica-context-switcher" 1>&2
   print_help
   exit 1
 elif [[ -z "${base_url}" ]]; then
-  echo_stderr "Please set the env var ICA_BASE_URL"
+  echo_stderr "Error: Please set the env var ICA_BASE_URL"
   print_help
   exit 1
 fi
@@ -140,5 +147,16 @@ file_id="$(get_file_id "${volume_name}" "${file_path}" "${access_token}" "${base
 # Collect presigned url
 presigned_url="$(get_presigned_url_from_file_id "${file_id}" "${access_token}" "${base_url}")"
 
-# Run links through docker
-run_links "${presigned_url}"
+# Present file
+if [[ "${to_stdout}" == "false" ]]; then
+  # Run links through docker
+  run_links "${presigned_url}"
+else
+  # Print to stdout
+  wget --output-document - "${presigned_url}" 2>/dev/null
+  # Check if we're in a pipe or not
+  if [ -t 1 ]; then
+    # If we're running in terminal, we want the user to have their console back
+    echo ""
+  fi
+fi
